path: '/work/sEMG-Net/datasets/'

mu: 255
image_size: 64
patch_size: 4
num_layers: 1
num_classes: 5
d_model: 192
num_heads: 12
mlp_dim: 384
channels: 1

lr: 0.0001
beta1: 0.9
beta2: 0.999
weight_decay: 0.001

batch_size: 128
num_epochs: 30
