path: '/work/datasets/hd_semg/'

image_size: 8
patch_size: 4
num_layers: 1
num_classes: 65
d_model: 192
num_heads: 12
mlp_dim: 384
channels: 128

lr: 1e-4
beta1: 0.9
beta2: 0.999
weight_decay: 0.001

batch_size: 128
num_epochs: 30
